includes("plugin_0", "plugin_1", "plugin_main")

target("UnitTestSPA")   
    set_kind("binary")
    add_deps("SPA", "plugin_0", "plugin_1", "plugin_main")
    add_files("UnitTestSPA.cpp")
    --before_build(function(target)
        --print("SPAUnitTest: Gen module infos")
        --os.exec("python3 SPA/anyToheader.py meta .json SPAUnitTest/")
        --os.exec("python3 SPA/ModuleCollector.py meta SPAUnitTest/")
    --end)